### ISSUE TITLE
Topological Consistency snippet

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/geonetwork-snippets#3]
This DQ snippet refuses to show in GeoNetwork 3.12 in the "Manage directory" menu, however, it can be searched for and selected when editing records in the portal and doesn't show any apparent issues.

**Comment by archaeogeek** [comment]
Closed by https://github.com/AstunTechnology/geonetwork-snippets/commit/5566a5ded5d37a42b6d13006ea34c848a88e1aba
