### ISSUE TITLE
Domain Consistency not displaying properly in GeoNetwork

### ISSUE THREAD

**Issue by alexarobu** [AstunTechnology/geonetwork-snippets#4]
When the Domain Consistency DQ snippet is loaded in GeoNetwork and added to a record it doesn't display the title properly in the record's editing interface (see inserted picture).

![Screenshot 2022-11-01 09 12 04](https://user-images.githubusercontent.com/36423106/199201495-15f24ccd-c446-4847-9b72-06631daea152.png)

**Comment by archaeogeek** [comment]
It seems to work for me OK?
![Screenshot from 2022-11-10 14-30-01](https://user-images.githubusercontent.com/1544849/201118300-f40a1465-3c35-476d-b4a1-a3822405f7eb.png)

**Comment by alexarobu** [comment]
It seems to show ok on my portal too now, what I thought was an issue was the `Conformity` title showing twice, instead of it saying `Domain Consistency` above where it says `Report` in your screenshot.

**Comment by archaeogeek** [comment]
Yeah, that probably does need resolving- it will be something in the gemini 2.3 labels file that needs changing

**Comment by archaeogeek** [comment]
@alexarobu have a look at the xml and then the labels.xml file in Gemini 2.3 to see if you can figure out what you would need to change to get the second conformity to display differently

**Comment by alexarobu** [comment]
Resolved

The issue was in the Gemini 2.3 `labels.xml` file - the `<label>` for the DQ_DomainConsistency element was set to "Conformity"

![image](https://user-images.githubusercontent.com/36423106/202182025-5cabf983-6993-4537-a14e-f661aec4f884.png)
